<?php

return [
    'states' => [
        'WV' => [
            'state' => 'West Virginia',
            'headline' => 'Coverage throughout the Huntington market and surrounding Putnam County communities.',
        ],
        'KY' => [
            'state' => 'Kentucky',
            'headline' => 'Local roofing coverage for Ashland and nearby Boyd and Carter County communities.',
        ],
        'OH' => [
            'state' => 'Ohio',
            'headline' => 'Service across Ironton, Portsmouth, and surrounding southern Ohio communities.',
        ],
    ],

    'cities' => [
        'huntington-wv' => [
            'city' => 'Huntington',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'huntington-wv',
            'rank' => 1,
            'population' => 46800,
            'population_label' => '~46,800',
            'intro' => 'Homeowners and business owners in Huntington count on Ridgeline Roofing for roof repairs, replacements, and storm damage response backed by clear communication and dependable scheduling.',
            'local_context' => 'From older neighborhoods near downtown to busy commercial properties across Cabell County, Huntington roofs need systems that can handle wind, rain, and year-round weather swings.',
            'service_focus' => 'We support Huntington with residential shingle and metal roofing, commercial flat roof work, emergency leak response, and fast inspections.',
            'nearby_areas' => ['Barboursville', 'Pea Ridge', 'Milton', 'Kenova', 'Hurricane'],
        ],
        'ashland-ky' => [
            'city' => 'Ashland',
            'state' => 'Kentucky',
            'state_abbr' => 'KY',
            'slug' => 'ashland-ky',
            'rank' => 2,
            'population' => 21600,
            'population_label' => '~21,600',
            'intro' => 'Ridgeline Roofing serves Ashland property owners with practical roofing solutions that prioritize long-term value, responsive service, and honest recommendations.',
            'local_context' => 'Ashland homes and businesses see everything from heavy summer storms to winter weather, so roofing systems here need dependable installation details and prompt repair support.',
            'service_focus' => 'In Ashland we handle residential roof replacement, roof repair, commercial roofing systems, gutter work, and storm-related inspections.',
            'nearby_areas' => ['Flatwoods', 'Russell', 'Grayson', 'Huntington', 'Ironton'],
        ],
        'portsmouth-oh' => [
            'city' => 'Portsmouth',
            'state' => 'Ohio',
            'state_abbr' => 'OH',
            'slug' => 'portsmouth-oh',
            'rank' => 3,
            'population' => 20000,
            'population_label' => '~20,000',
            'intro' => 'Portsmouth customers choose Ridgeline Roofing for straightforward inspections, reliable workmanship, and roofing systems built to protect both homes and commercial properties.',
            'local_context' => 'Properties in and around Portsmouth need roofing that stands up to river-valley humidity, severe weather, and the wear that comes from changing seasons in southern Ohio.',
            'service_focus' => 'We help Portsmouth with residential reroofs, leak repairs, commercial flat roof service, and storm damage restoration planning.',
            'nearby_areas' => ['Wheelersburg', 'South Point', 'Ironton', 'Burlington', 'Ashland'],
        ],
        'ironton-oh' => [
            'city' => 'Ironton',
            'state' => 'Ohio',
            'state_abbr' => 'OH',
            'slug' => 'ironton-oh',
            'rank' => 4,
            'population' => 10600,
            'population_label' => '~10,600',
            'intro' => 'Ridgeline Roofing works with Ironton homeowners and businesses that want experienced roofing crews, fair scopes, and responsive follow-through from inspection to completion.',
            'local_context' => 'From historic homes to commercial buildings near the river, Ironton roofs benefit from proactive repair work and replacement systems designed for lasting performance.',
            'service_focus' => 'Our Ironton work includes shingle replacement, metal roofing, commercial roof repair, gutter services, and storm damage support.',
            'nearby_areas' => ['South Point', 'Burlington', 'Wheelersburg', 'Ashland', 'Huntington'],
        ],
        'flatwoods-ky' => [
            'city' => 'Flatwoods',
            'state' => 'Kentucky',
            'state_abbr' => 'KY',
            'slug' => 'flatwoods-ky',
            'rank' => 5,
            'population' => 7200,
            'population_label' => '~7,200',
            'intro' => 'Flatwoods property owners trust Ridgeline Roofing for dependable roof replacements and repairs that are clearly explained and professionally executed.',
            'local_context' => 'Flatwoods homes often need roofing solutions that balance curb appeal, storm protection, and long-term maintenance value for busy families and local businesses.',
            'service_focus' => 'We serve Flatwoods with residential reroofing, storm repairs, gutter upgrades, and commercial roofing support across the surrounding area.',
            'nearby_areas' => ['Ashland', 'Russell', 'Grayson', 'Portsmouth', 'Ironton'],
        ],
        'hurricane-wv' => [
            'city' => 'Hurricane',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'hurricane-wv',
            'rank' => 6,
            'population' => 7300,
            'population_label' => '~7,300',
            'intro' => 'Ridgeline Roofing helps Hurricane homeowners and businesses protect their properties with quality roof systems, quick inspections, and responsive repair work.',
            'local_context' => 'Growing neighborhoods and commercial corridors in Hurricane need roofing solutions that can handle West Virginia weather while keeping projects organized and on schedule.',
            'service_focus' => 'In Hurricane we provide roof replacement, leak repair, storm damage service, and commercial flat roof support with a local-service mindset.',
            'nearby_areas' => ['Milton', 'Barboursville', 'Huntington', 'Pea Ridge', 'Kenova'],
        ],
        'pea-ridge-wv' => [
            'city' => 'Pea Ridge',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'pea-ridge-wv',
            'rank' => 7,
            'population' => 6600,
            'population_label' => '~6,600',
            'intro' => 'Pea Ridge customers work with Ridgeline Roofing when they want a contractor that shows up prepared, communicates clearly, and focuses on lasting results.',
            'local_context' => 'Whether the need is a residential replacement or a timely repair, Pea Ridge properties benefit from roofing systems built for the region’s rain, wind, and seasonal changes.',
            'service_focus' => 'We support Pea Ridge with residential roofing, commercial roof service, gutter work, and storm-related inspections.',
            'nearby_areas' => ['Huntington', 'Barboursville', 'Milton', 'Kenova', 'Hurricane'],
        ],
        'wheelersburg-oh' => [
            'city' => 'Wheelersburg',
            'state' => 'Ohio',
            'state_abbr' => 'OH',
            'slug' => 'wheelersburg-oh',
            'rank' => 8,
            'population' => 6300,
            'population_label' => '~6,300',
            'intro' => 'Ridgeline Roofing provides Wheelersburg property owners with honest roofing guidance, dependable installation practices, and responsive repair service.',
            'local_context' => 'Wheelersburg roofs need to hold up through severe weather and year-round exposure, which is why proper materials and careful installation details matter here.',
            'service_focus' => 'We help Wheelersburg with roof repairs, full replacements, storm damage service, and commercial roofing support across the local market.',
            'nearby_areas' => ['Portsmouth', 'Ironton', 'South Point', 'Flatwoods', 'Ashland'],
        ],
        'barboursville-wv' => [
            'city' => 'Barboursville',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'barboursville-wv',
            'rank' => 9,
            'population' => 4300,
            'population_label' => '~4,300',
            'intro' => 'Barboursville residents and business owners rely on Ridgeline Roofing for practical roofing solutions, prompt communication, and workmanship designed to last.',
            'local_context' => 'From residential neighborhoods to high-traffic commercial properties, Barboursville roofs need reliable service plans and crews that respect project timelines.',
            'service_focus' => 'Our Barboursville projects include shingle roofing, metal roofing, flat roof repairs, gutter work, and storm damage restoration support.',
            'nearby_areas' => ['Huntington', 'Pea Ridge', 'Milton', 'Kenova', 'Hurricane'],
        ],
        'grayson-ky' => [
            'city' => 'Grayson',
            'state' => 'Kentucky',
            'state_abbr' => 'KY',
            'slug' => 'grayson-ky',
            'rank' => 10,
            'population' => 4000,
            'population_label' => '~4,000',
            'intro' => 'Ridgeline Roofing serves Grayson customers who want clear scopes, strong workmanship, and roofing recommendations that make sense for their property and budget.',
            'local_context' => 'Grayson homeowners and local businesses need roofing systems that can handle storm exposure, aging roof conditions, and the maintenance demands of the region.',
            'service_focus' => 'We provide Grayson with roof replacement, roof repair, storm-related inspections, and commercial roofing support when fast response matters.',
            'nearby_areas' => ['Ashland', 'Flatwoods', 'Russell', 'Portsmouth', 'Ironton'],
        ],
        'russell-ky' => [
            'city' => 'Russell',
            'state' => 'Kentucky',
            'state_abbr' => 'KY',
            'slug' => 'russell-ky',
            'rank' => 11,
            'population' => 3400,
            'population_label' => '~3,400',
            'intro' => 'Russell property owners turn to Ridgeline Roofing for experienced roof replacement and repair service delivered with dependable follow-up and honest communication.',
            'local_context' => 'Russell homes and businesses see the same tri-state weather pressures as the rest of the region, making preventative roof care and well-planned replacements especially important.',
            'service_focus' => 'We support Russell with residential reroofing, leak repair, commercial roofing service, and fast storm inspections.',
            'nearby_areas' => ['Ashland', 'Flatwoods', 'Grayson', 'Ironton', 'Portsmouth'],
        ],
        'south-point-oh' => [
            'city' => 'South Point',
            'state' => 'Ohio',
            'state_abbr' => 'OH',
            'slug' => 'south-point-oh',
            'rank' => 12,
            'population' => 3300,
            'population_label' => '~3,300',
            'intro' => 'Ridgeline Roofing helps South Point homeowners and commercial property owners solve roofing problems with responsive service and quality installation practices.',
            'local_context' => 'South Point properties need roofing systems that can handle moisture, wind, and day-to-day wear while still delivering strong long-term value.',
            'service_focus' => 'In South Point we handle roof replacement, roof repair, storm response, gutter service, and commercial flat roof work.',
            'nearby_areas' => ['Ironton', 'Huntington', 'Portsmouth', 'Burlington', 'Wheelersburg'],
        ],
        'kenova-wv' => [
            'city' => 'Kenova',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'kenova-wv',
            'rank' => 13,
            'population' => 3000,
            'population_label' => '~3,000',
            'intro' => 'Kenova customers choose Ridgeline Roofing for roofing work that is clearly scoped, professionally managed, and built around long-term protection.',
            'local_context' => 'Homes and businesses in Kenova benefit from roofing crews that understand the tri-state market and can respond quickly when leaks, storm damage, or replacement needs show up.',
            'service_focus' => 'We serve Kenova with residential and commercial roofing, storm-related repairs, leak diagnostics, and free inspections.',
            'nearby_areas' => ['Huntington', 'Pea Ridge', 'Barboursville', 'Milton', 'South Point'],
        ],
        'burlington-oh' => [
            'city' => 'Burlington',
            'state' => 'Ohio',
            'state_abbr' => 'OH',
            'slug' => 'burlington-oh',
            'rank' => 14,
            'population' => 3000,
            'population_label' => '~3,000',
            'intro' => 'Ridgeline Roofing provides Burlington with reliable roofing service focused on craftsmanship, responsive communication, and practical solutions for local properties.',
            'local_context' => 'Burlington property owners need roofing systems that can handle weather exposure and day-to-day wear while minimizing disruption and future maintenance headaches.',
            'service_focus' => 'Our Burlington work includes roof replacement, leak repair, storm inspections, gutter upgrades, and commercial roofing support.',
            'nearby_areas' => ['Ironton', 'South Point', 'Portsmouth', 'Wheelersburg', 'Huntington'],
        ],
        'milton-wv' => [
            'city' => 'Milton',
            'state' => 'West Virginia',
            'state_abbr' => 'WV',
            'slug' => 'milton-wv',
            'rank' => 15,
            'population' => 2500,
            'population_label' => '~2,500',
            'intro' => 'Milton homeowners and business owners trust Ridgeline Roofing for straightforward roofing advice, strong workmanship, and reliable local service.',
            'local_context' => 'Milton roofs need to hold up through seasonal storms and everyday exposure, which makes careful repair work and well-installed replacement systems especially valuable.',
            'service_focus' => 'We help Milton with roof replacement, roof repair, storm damage service, commercial flat roof support, and preventative inspections.',
            'nearby_areas' => ['Hurricane', 'Barboursville', 'Huntington', 'Pea Ridge', 'Kenova'],
        ],
    ],
];
